import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service – PromptForge',
  description: 'PromptForge terms of service. Rules and guidelines for using the platform.',
}

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <Link href="/" className="text-xs text-zinc-dim hover:text-amber font-mono transition-colors mb-8 block">← Back to Home</Link>
      <h1 className="text-3xl font-extrabold text-cream mb-2" style={{ fontFamily: 'var(--font-syne)' }}>Terms of Service</h1>
      <p className="text-xs text-zinc-dim font-mono mb-12">Last updated: January 1, 2025</p>

      <div className="space-y-8 text-sm text-zinc leading-relaxed">
        {[
          { h: '1. Acceptance', p: `By accessing promptforge.ai ("the Site"), you agree to these Terms of Service. If you do not agree, please discontinue use. We reserve the right to update these terms; continued use constitutes acceptance of changes.` },
          { h: '2. Use of the Service', p: `PromptForge provides a free AI prompt generation tool. You may use the prompts generated for any personal or commercial purpose. You may not use the Site to generate prompts intended to cause harm, facilitate illegal activity, spread misinformation, or violate the terms of the AI services you use the prompts with.` },
          { h: '3. Intellectual Property', p: `The prompts generated by this tool are provided for your unrestricted use. The underlying software, design system, and template library of PromptForge are proprietary. You may not reproduce, scrape, or redistribute the tool itself or its underlying prompt templates.` },
          { h: '4. No Warranties', p: `The Service is provided "as is" and "as available." We make no warranties about the accuracy, reliability, or suitability of generated prompts for any specific purpose. AI outputs based on these prompts may vary significantly by model and context.` },
          { h: '5. Limitation of Liability', p: `PromptForge and its operators shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service, including any AI-generated content produced using our prompts.` },
          { h: '6. Third-Party AI Services', p: `PromptForge generates prompts for use with third-party AI services (ChatGPT, Midjourney, Claude, etc.). We are not affiliated with these services and are not responsible for their outputs, policies, or changes to their platforms.` },
          { h: '7. Governing Law', p: `These Terms are governed by applicable law. Any disputes shall first be attempted through good-faith negotiation between the parties.` },
          { h: '8. Contact', p: `For terms-related questions: legal@promptforge.ai` },
        ].map((s, i) => (
          <div key={i}>
            <h2 className="text-base font-bold text-cream mb-2" style={{ fontFamily: 'var(--font-syne)' }}>{s.h}</h2>
            <p>{s.p}</p>
          </div>
        ))}
      </div>
    </div>
  )
}
